DataIngestionConfig:
  train_data_path: "artifacts/train.csv"
  test_data_path: "artifacts/test.csv"
  raw_data_path: "artifacts/data.csv"
  input_data_path: "src/notebook/data/stud.csv"
  test_size: 0.2
  random_state: 42